const express = require("express");
const cors = require("cors");
const app = express();

app.use(cors());
app.use(express.json());

// AUTH ROUTES

// POST NEW USER

// POST LOGIN USER

// GET AUTHENTICATED USER

// PRODUCTION ROUTES

// GET ALL PRODUCTIONS

// POST NEW PRODUCTION

// GET PRODUCTION BY ID

// PATCH PRODUCTION BY ID - EDIT TITLE, DATES, COMPANY MEMBERS, VENUE

// DELETE PRODUCTION BY ID

// COMPANY MEMBER ROUTES

// GET ALL COMPANY MEMBERS BY PRODUCTION ID

// POST NEW COMPANY MEMBER TO PRODUCTION BY EMAIL

// DELETE COMPANY MEMBER BY ID

// REHEARSAL ROUTES

// GET ALL REHEARSALS BY PRODUCTION ID

// POST NEW REHEARSAL TO PRODUCTION BY ID

// PATCH REHEARSAL BY ID - EDIT DATE, TIME, LOCATION, NOTES

// GET ALL REHEARSALS BY USER_ID

// DELETE A REHEARSAL BY ID

// CALL ROUTES

// GET ALL CALLS BY REHEARSAL ID

// POST NEW USER TO REHEARSAL BY ID

// DELETE USER FROM REHEARSAL BY ID

// PATCH - CONFIRM OR UNCONFIRM USER ATTENDANCE BY REHEARSAL ID AND USER ID

// ERRORS

app.use((err, req, res, next) => {
  console.error(err);
  res
    .status(err.status || 500)
    .send({ msg: err.msg || "Internal server error" });
});

module.exports = app;
